name: Clippy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Toolchain setup
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: Clippy
        run: cargo clippy --all-features -- -Dwarnings
